Asumiendo que todas las bases se ven de forma semejante, o sea que todas contengan la informacion segregada de la misma forma, voy a ordenar solo un año y el resto se debe resolver solo.

In [1]:
import pandas as pd
import numpy as np

# 2017

## Cirugias

In [193]:
cirugias=pd.read_csv('Cirugias\ConsultaH_Intervenciones_Quirurgicas_2017_v1.csv',encoding='ISO-8859-1')

In [194]:
cirugias.replace('NE_0002', np.nan, inplace=True)
cirugias.replace('NE_0001', np.nan, inplace=True)
cirugias.fillna(0,inplace=True)

In [195]:
cirugias.iloc[:,10:]=cirugias.iloc[:,10:].apply(pd.to_numeric,errors='coerce')

In [199]:
cirugias.head()

,CO_IPRESS,ANHO,MES,DE_PROGRAMC,TOTAL_CIRUJ_MAY,TOTAL_CIRUJ_MEN,HORAS_PROGRAMADAS,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND
0,1,2017,1,3,207,30.0,315.0,301.0,0,5
1,1,2017,2,3,203,25.0,324.0,311.0,0,4
2,1,2017,3,3,190,28.0,321.0,315.0,0,3
3,1,2017,4,3,177,26.0,326.0,318.0,0,2
4,1,2017,5,3,167,26.0,306.0,298.0,0,3

In [197]:
cirugias_to_sum = cirugias.columns[10:]
cirugias=cirugias.groupby(['CO_IPRESS','ANHO','MES'])[cirugias_to_sum].sum()

In [198]:
cirugias=cirugias.reset_index()

## Procedimientos

In [200]:
procedimientos=pd.read_csv("Procedimientos\ConsultaG_Procedimientos_2017_v1.csv",encoding='ISO-8859-1')

C:\Users\gonza\AppData\Local\Temp\ipykernel_11100\76611569.py:1: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  procedimientos=pd.read_csv("Procedimientos\ConsultaG_Procedimientos_2017_v1.csv",encoding='ISO-8859-1')

In [201]:
procedimientos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PROCEDIMIENTO,PROCEDIMIENTO,TOTAL,ID_CODIGO,DES_DESCRIPCION
0,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,94010,"Espirometría, incluyendo reporte gráfico, capa...",1,223800,CONSULTA EXTERNA-NEUMOLOGÍA
1,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,96372,"Inyección terapéutica, profiláctica o diagnóst...",1,250100,UNIDAD DE CUIDADOS CRITICOS UNIDAD DE CUIDADO...
2,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,86704,Anticuerpo contra el antígeno de la nucleocáps...,2,150000,PATOLOGÍA CLÍNICA (LABORATORIO CLÍNICO)
3,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,84450,Aspartato amino transferasa (AST) (SGOT),1,150000,PATOLOGÍA CLÍNICA (LABORATORIO CLÍNICO)
4,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,93784,"Control ambulatorio de la presión arterial, me...",3,222500,CONSULTA EXTERNA-CARDIOLOGÍA

In [202]:
procedimientos=procedimientos.groupby(['CO_IPRESS','MES','ANHO'])['ID_PROCEDIMIENTO'].count().reset_index()

In [203]:
procedimientos

      CO_IPRESS  MES  ANHO  ID_PROCEDIMIENTO
0             1    1  2017               629
1             1    2  2017               580
2             1    3  2017               542
3             1    4  2017               534
4             1    5  2017               603
...         ...  ...   ...               ...
9493      23159   11  2017              2921
9494      23159   12  2017              3291
9495      23918    8  2017                12
9496      23918    9  2017                12
9497      23918   10  2017                13

[9498 rows x 4 columns]

## Complicaciones

In [204]:
complicaciones=pd.read_csv("Complcaciones\ConsultaF_Consolidado_Eventos_2017_v1.csv",encoding='ISO-8859-1')

In [205]:
complicaciones.replace('NE_0002', np.nan, inplace=True)
complicaciones.replace('NE_0001', np.nan, inplace=True)
complicaciones.fillna(0,inplace=True)

In [206]:
complicaciones.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,EVENTOS,CANT_EVENTOS
0,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Nacidos vivos con bajo peso al nacer (< 2500 grs),3
1,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Nacidos vivos con edad gestacional menor a 37 ...,3
2,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de Infeccion Intrahosp...,1
3,2017,8,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de infeccion de herida ...,1
4,2017,8,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de infeccion de herida ...,1

In [207]:
complicaciones.iloc[:,-1]=complicaciones.iloc[:,-1].apply(pd.to_numeric)

In [208]:
complicaciones = pd.pivot_table(complicaciones, values='CANT_EVENTOS', index=['ANHO', 'MES', 'UBIGEO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'SECTOR', 'CATEGORIA', 'CO_IPRESS', 'RAZON_SOC'], columns='EVENTOS', aggfunc='sum', fill_value=0)
complicaciones.reset_index(inplace=True)
complicaciones

EVENTOS,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,ESSALUD,II-1,9066,HOSPITAL HIGOS URCO,...,0,0,0,0,164,0,0,24,0,21
1,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,GOBIERNO REGIONAL,II-2,4838,HOSPITAL REGIONAL VIRGEN DE FATIMA,...,0,0,0,0,18,0,2,0,0,0
2,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,13226,POLICLINICO PNP CHACHAPOYAS,...,0,0,0,0,0,0,0,0,0,0
3,2017,1,10201,AMAZONAS,BAGUA,BAGUA,ESSALUD,II-1,9068,HOSPITAL I HEROES DEL CENEPA,...,0,0,0,0,52,0,0,15,15,15
4,2017,1,10201,AMAZONAS,BAGUA,BAGUA,GOBIERNO REGIONAL,II-1,5044,HOSPITAL DE APOYO GUSTAVO LANATTA LUJAN,...,0,0,0,0,124,1,0,15,16,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9671,2017,12,240304,TUMBES,ZARUMILLA,PAPAYAL,GOBIERNO REGIONAL,I-3,1891,C.S. PAPAYAL,...,0,0,0,0,7,0,0,0,0,0
9672,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,ESSALUD,II-2,9600,HOSPITAL II PUCALLPA- ESSALUD,...,0,0,0,0,512,0,0,126,79,102
9673,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,PRIVADO,I-3,10505,SERVICIOS GENERALES SERFARMED SYS S.A,...,0,0,0,0,0,0,0,0,0,0
9674,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,10148,POLICLINICO SANIDAD DE LA POLICIA NACIONAL DEL...,...,0,0,0,0,0,0,0,0,0,0
9675,2017,12,250105,UCAYALI,CORONEL PORTILLO,YARINACOCHA,GOBIERNO REGIONAL,II-2,5577,HOSPITAL AMAZONICO - YARINACOCHA,...,0,0,0,0,215,0,3,44,122,193

In [214]:
colums_to_sum=complicaciones.columns[-21:]

In [216]:
complicaciones.groupby(['CO_IPRESS','MES','ANHO'])[colums_to_sum].sum().reset_index()

EVENTOS,CO_IPRESS,MES,ANHO,Casos Nuevos de Gestantes con diagnostico confirmado de Tuberculosis,Casos Nuevos de Gestantes con diagnostico confirmado de infección HIV.,Casos Nuevos de TBC Multidrogoresistente (MDR o XDR).,Casos Nuevos de TBC pulmonar en el personal del EESS,Casos nuevos de infeccion HIV.,Fallecimientos en todos los servicios.,Nacidos vivos con bajo peso al nacer (< 2500 grs),...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,1,1,2017,0,0,0,0,2,18,10,...,0,0,0,0,225,0,11,341,0,0
1,1,2,2017,0,0,0,0,7,19,11,...,0,1,0,4,267,0,6,256,0,0
2,1,3,2017,0,0,0,0,5,5,3,...,0,1,0,8,307,0,4,206,0,0
3,1,4,2017,0,0,0,0,4,10,3,...,0,0,0,0,334,0,4,206,0,0
4,1,5,2017,0,0,0,0,0,12,1,...,0,0,0,0,353,0,4,260,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9671,23159,12,2017,0,0,0,0,3,0,24,...,0,7,0,0,0,0,1,293,121,200
9672,23578,12,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9673,23918,8,2017,0,0,0,0,0,0,0,...,0,0,0,0,17,0,0,0,0,0
9674,23918,9,2017,0,0,0,0,0,0,0,...,0,0,0,0,14,0,0,0,0,0
9675,23918,10,2017,0,0,0,0,0,0,0,...,0,0,0,0,21,0,0,0,0,0

## Nacimientos

In [129]:
nacimientos=pd.read_csv("Nacimientos\ConsultaE_Consolidado_Partos_2017_v1_0.csv",encoding='ISO-8859-1')

In [130]:
nacimientos.replace('NE_0002', np.nan, inplace=True)
nacimientos.replace('NE_0001', np.nan, inplace=True)
nacimientos.fillna(0,inplace=True)

In [131]:
nac_red=nacimientos.copy()
nacimientos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PARTO,TIPO_PARTO,PARTOS_TOTAL,PARTOS_VIVOS,PARTOS_MUERTOS
0,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0
1,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0
2,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,01,VAGINAL,0,0,0
3,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,01,VAGINAL,11,11,0
4,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0

In [132]:
nacimientos.iloc[:,-3:]=nacimientos.iloc[:,-3:].apply(pd.to_numeric)

In [133]:
import pandas as pd

nacimientos['Partos_CESAREA'] = 0
nacimientos['Partos_vivos_CESAREA'] = 0
nacimientos['Partos_muertos_CESAREA'] = 0
nacimientos['Partos_VAGINAL'] = 0
nacimientos['Partos_vivos_VAGINAL'] = 0
nacimientos['Partos_muertos_VAGINAL'] = 0

cesarea_condition = nacimientos['TIPO_PARTO'] == 'CESAREA'
vaginal_condition = nacimientos['TIPO_PARTO'] == 'VAGINAL'

nacimientos.loc[cesarea_condition, 'Partos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_TOTAL']
nacimientos.loc[vaginal_condition, 'Partos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_TOTAL']

nacimientos.loc[cesarea_condition, 'Partos_vivos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_VIVOS']
nacimientos.loc[cesarea_condition, 'Partos_muertos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_MUERTOS']

nacimientos.loc[vaginal_condition, 'Partos_vivos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_VIVOS']
nacimientos.loc[vaginal_condition, 'Partos_muertos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_MUERTOS']

nacimientos.drop(['PARTOS_TOTAL','PARTOS_VIVOS','PARTOS_MUERTOS','ID_PARTO','TIPO_PARTO'],axis=1,inplace=True)

In [135]:
nacimientos

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,Partos_CESAREA,Partos_vivos_CESAREA,Partos_muertos_CESAREA,Partos_VAGINAL,Partos_vivos_VAGINAL,Partos_muertos_VAGINAL
0,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
1,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
2,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
3,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,11,11,0
4,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18677,2017,5,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18678,2017,10,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18679,2017,12,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18680,2017,7,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18681,2017,12,20102,ANCASH,HUARAZ,COCHABAMBA,GOBIERNO REGIONAL,I-2,1730,PUESTO DE SALUD COCHABAMBA,0,0,0,0,0,0

In [142]:
nacimientos=nacimientos.groupby(['CO_IPRESS','MES'])[['Partos_CESAREA','Partos_VAGINAL','Partos_vivos_CESAREA','Partos_vivos_VAGINAL','Partos_muertos_CESAREA','Partos_muertos_VAGINAL']].sum()
nacimientos=nacimientos.reset_index()

In [143]:
nacimientos

,CO_IPRESS,MES,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,99,241,94,240,6,0
1,1,2,65,191,75,196,0,0
2,1,3,73,190,74,196,0,0
3,1,4,90,180,88,181,2,0
4,1,5,101,192,100,192,1,0
...,...,...,...,...,...,...,...,...
9884,23159,12,160,151,161,146,2,5
9885,23578,12,0,0,0,0,0,0
9886,23918,8,6,1,6,1,0,0
9887,23918,9,5,2,5,2,0,0
9888,23918,10,5,2,5,2,0,0

In [112]:
nac_red[nac_red['CO_IPRESS']==3]

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PARTO,TIPO_PARTO,PARTOS_TOTAL,PARTOS_VIVOS,PARTOS_MUERTOS
18034,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,7,1
18035,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,120,120,0
18036,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,34,33,2
18037,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,158,158,0
18038,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,6,3
18039,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,130,130,0
18040,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,38,33,6
18041,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,148,148,0
18042,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,15,11,6
18043,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,148,148,0
18044,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,52,54,3
18045,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,139,139,0
18046,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,2,4
18047,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,132,132,0
18048,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,33,34,2
18049,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,156,156,0
18050,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,7,3
18051,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,134,134,0
18052,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,59,60,1
18053,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,137,137,0
18054,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,11,1
18055,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,124,124,0
18056,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,22,22,1
18057,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,147,147,0
18058,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,6,3
18059,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,122,122,0
18060,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,34,33,2
18061,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,133,133,0
18062,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,11,9,5
18063,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,114,114,0
18064,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,32,32,1
18065,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,118,118,0
18066,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,4,3,1
18067,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,113,117,0
18068,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,55,54,1
18069,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,101,101,0
18070,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,8,0
18071,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,103,103,2
18072,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,67,71,1
18073,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,103,103,0
18074,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,11,16,2
18075,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,135,135,0
18076,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,5,0,5
18077,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,175,175,0
18078,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,9,0
18079,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,154,154,0
18080,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,33,32,2
18081,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,146,146,0

## HospxEsp

In [174]:
espe=pd.read_csv("Espe\ConsultaD1_Hospitalizaciones_Especialidad_2017_v1.csv",encoding='ISO-8859-1')

C:\Users\gonza\AppData\Local\Temp\ipykernel_11100\958217491.py:1: DtypeWarning: Columns (10,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  espe=pd.read_csv("Espe\ConsultaD1_Hospitalizaciones_Especialidad_2017_v1.csv",encoding='ISO-8859-1')

In [175]:
espe.replace('NE_0002', np.nan, inplace=True)
espe.replace('NE_0001', np.nan, inplace=True)
espe.fillna(0,inplace=True)

In [176]:
espe.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_HOSPITALIZACION,HOSPITALIZACION,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,2017,8,150112,LIMA,LIMA,INDEPENDENCIA,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-2,12741,POSTA MEDICA PNP INDEPENDENCIA,0,0,0,0,0,0,0,0,0
1,2017,8,150135,LIMA,LIMA,SAN MARTIN DE PORRES,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,11876,UNIDAD EJECUTORA 020: SANIDAD DE LA PNP,0,0,0,0,0,0,0,0,0
2,2017,8,150101,LIMA,LIMA,LIMA,PRIVADO,II-2,8281,CLINICAS MAISON DE SANTE SOCIEDAD ANONIMA,240000,HOSPITALIZACIÓN,40,40,195,207,23,713,0
3,2017,8,150101,LIMA,LIMA,LIMA,PRIVADO,II-2,8281,CLINICAS MAISON DE SANTE SOCIEDAD ANONIMA,240100,HOSPITALIZACIÓN QUIRÚRGICA CIRUGÍA GENERAL,37,37,165,223,26,806,0
4,2017,7,200104,PIURA,PIURA,CASTILLA,PRIVADO,II-E,13165,CENTRO DE REPOSO SAN JUAN DE DIOS,242202,HOSPITALIZACIÓN DE MEDICINA PSIQUIATRÍA PSIQUI...,48,52,1597,1424,56,1736,0

In [177]:
espe.iloc[:,-7:]=espe.iloc[:,-7:].apply(pd.to_numeric)

In [178]:
espe=espe.groupby(['CO_IPRESS','MES'])[['NRO_TOTAL_HOSPIT_ING','NRO_TOTAL_HOSPIT_EGR','NRO_TOTAL_ESTANCIAS','NRO_TOTAL_PACIENTES_CAMAS','NRO_TOTAL_CAMAS','NRO_TOTAL_CAMAS_DISPONIB','NRO_TOTAL_FALLECIDOS']].sum()

In [180]:
espe=espe.reset_index()
espe

,CO_IPRESS,MES,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,1,1,736,801,2762,3277,120,3720,18
1,1,2,555,632,2179,2181,120,3360,8
2,1,3,542,614,1994,1859,120,3720,5
3,1,4,580,661,2274,1995,120,3600,10
4,1,5,651,718,2507,1995,120,3720,12
...,...,...,...,...,...,...,...,...,...
10159,23159,12,472,459,4452,3417,152,4712,29
10160,23578,12,0,0,0,0,0,0,0
10161,23918,8,31,36,49,49,12,360,0
10162,23918,9,33,38,52,52,12,360,0
10163,23918,10,38,36,54,54,12,360,0

## Recursos

In [120]:
recursos=pd.read_csv("Recursos\ConsultaA_Recurso_Salud_2017_v1.csv",encoding='ISO-8859-1')

In [122]:
recursos.replace('NE_0002', np.nan, inplace=True)
recursos.replace('NE_0001', np.nan, inplace=True)
recursos.fillna(0,inplace=True)

In [123]:
recursos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,...,CA_ENFERMERAS,CA_ODONTOLOGOS,CA_PSICOLOGOS,CA_NUTRICIONISTAS,CA_TECNOLOGOS_MEDICOS,CA_OBSTETRICES,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS
0,2017,12,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
1,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,9,3,3,2,1,10,1,2,2,1
2,2017,11,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
3,2017,10,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
4,2017,8,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,9,3,3,2,1,10,1,2,2,1

In [124]:
recursos.iloc[:,10:26]=recursos.iloc[:,10:26].apply(pd.to_numeric)

In [128]:
columns_to_sum = recursos.columns[10:26]
recursos = recursos.groupby(['CO_IPRESS', 'MES'])[columns_to_sum].sum()
recursos = recursos.reset_index()
recursos

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,CA_PSICOLOGOS,CA_NUTRICIONISTAS,CA_TECNOLOGOS_MEDICOS,CA_OBSTETRICES,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS
0,1,1,31,42,120,61,0,17,92,4,2,3,1,38,7,252,3,1
1,1,2,31,42,120,60,0,17,88,4,2,3,1,37,7,252,5,1
2,1,3,31,42,120,60,0,17,88,4,2,3,1,37,7,252,5,1
3,1,4,31,42,120,58,0,18,88,4,2,3,1,33,6,252,5,1
4,1,5,31,42,120,58,0,18,88,4,2,3,1,33,6,252,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9974,23159,12,27,39,122,144,0,0,148,6,4,6,43,37,16,280,1,2
9975,23578,12,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0
9976,23918,8,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0
9977,23918,9,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0
9978,23918,10,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0

## base final

In [171]:
nacimientos.head()

,CO_IPRESS,MES,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,99,241,94,240,6,0
1,1,2,65,191,75,196,0,0
2,1,3,73,190,74,196,0,0
3,1,4,90,180,88,181,2,0
4,1,5,101,192,100,192,1,0

In [173]:
df = pd.merge(recursos, nacimientos, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,31,42,120,61,0,17,92,4,...,7,252,3,1,99,241,94,240,6,0
1,1,2,31,42,120,60,0,17,88,4,...,7,252,5,1,65,191,75,196,0,0
2,1,3,31,42,120,60,0,17,88,4,...,7,252,5,1,73,190,74,196,0,0
3,1,4,31,42,120,58,0,18,88,4,...,6,252,5,1,90,180,88,181,2,0
4,1,5,31,42,120,58,0,18,88,4,...,6,252,5,1,101,192,100,192,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9783,23159,12,27,39,122,144,0,0,148,6,...,16,280,1,2,160,151,161,146,2,5
9784,23578,12,0,0,0,1,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
9785,23918,8,2,4,12,5,0,0,5,0,...,1,9,3,0,6,1,6,1,0,0
9786,23918,9,2,4,12,5,0,0,5,0,...,1,9,3,0,5,2,5,2,0,0
9787,23918,10,2,4,12,5,0,0,5,0,...,1,9,3,0,5,2,5,2,0,0

In [217]:
df = pd.merge(df, cirugias, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CA_OTROS_PROF,CA_AMBULANCIAS,ANHO,DE_PROGRAMC,TOTAL_CIRUJ_MAY,TOTAL_CIRUJ_MEN,HORAS_PROGRAMADAS,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND
0,1,1,31,42,120,61,0,17,92,4,...,3,1,2017,3,207,30.0,315.0,301.0,0,5
1,1,2,31,42,120,60,0,17,88,4,...,5,1,2017,3,203,25.0,324.0,311.0,0,4
2,1,3,31,42,120,60,0,17,88,4,...,5,1,2017,3,190,28.0,321.0,315.0,0,3
3,1,4,31,42,120,58,0,18,88,4,...,5,1,2017,3,177,26.0,326.0,318.0,0,2
4,1,5,31,42,120,58,0,18,88,4,...,5,1,2017,3,167,26.0,306.0,298.0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9623,23159,12,27,39,122,144,0,0,148,6,...,1,2,2017,3,353,75.0,480.0,715.0,0,11
9624,23578,12,0,0,0,1,0,0,0,0,...,0,0,2017,0,0,0.0,0.0,0.0,0.0,0
9625,23918,8,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,31.0,87.0,74.0,0,0
9626,23918,9,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,33.0,99.0,79.0,0,0
9627,23918,10,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,38.0,144.0,91.0,0,0

In [218]:
df = pd.merge(df, espe, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,1,1,31,42,120,61,0,17,92,4,...,301.0,0,5,736,801,2762,3277,120,3720,18
1,1,2,31,42,120,60,0,17,88,4,...,311.0,0,4,555,632,2179,2181,120,3360,8
2,1,3,31,42,120,60,0,17,88,4,...,315.0,0,3,542,614,1994,1859,120,3720,5
3,1,4,31,42,120,58,0,18,88,4,...,318.0,0,2,580,661,2274,1995,120,3600,10
4,1,5,31,42,120,58,0,18,88,4,...,298.0,0,3,651,718,2507,1995,120,3720,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9567,23159,12,27,39,122,144,0,0,148,6,...,715.0,0,11,472,459,4452,3417,152,4712,29
9568,23578,12,0,0,0,1,0,0,0,0,...,0.0,0.0,0,0,0,0,0,0,0,0
9569,23918,8,2,4,12,5,0,0,5,0,...,74.0,0,0,31,36,49,49,12,360,0
9570,23918,9,2,4,12,5,0,0,5,0,...,79.0,0,0,33,38,52,52,12,360,0
9571,23918,10,2,4,12,5,0,0,5,0,...,91.0,0,0,38,36,54,54,12,360,0

In [219]:
df = pd.merge(df, procedimientos, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CIRUJ_SUSPEND,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS,ANHO_y,ID_PROCEDIMIENTO
0,1,1,31,42,120,61,0,17,92,4,...,5,736,801,2762,3277,120,3720,18,2017,629
1,1,2,31,42,120,60,0,17,88,4,...,4,555,632,2179,2181,120,3360,8,2017,580
2,1,3,31,42,120,60,0,17,88,4,...,3,542,614,1994,1859,120,3720,5,2017,542
3,1,4,31,42,120,58,0,18,88,4,...,2,580,661,2274,1995,120,3600,10,2017,534
4,1,5,31,42,120,58,0,18,88,4,...,3,651,718,2507,1995,120,3720,12,2017,603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9313,23159,11,27,39,122,142,0,0,189,6,...,9,503,455,3966,3288,152,4560,10,2017,2921
9314,23159,12,27,39,122,144,0,0,148,6,...,11,472,459,4452,3417,152,4712,29,2017,3291
9315,23918,8,2,4,12,5,0,0,5,0,...,0,31,36,49,49,12,360,0,2017,12
9316,23918,9,2,4,12,5,0,0,5,0,...,0,33,38,52,52,12,360,0,2017,12
9317,23918,10,2,4,12,5,0,0,5,0,...,0,38,36,54,54,12,360,0,2017,13

In [220]:
df = pd.merge(df, complicaciones, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,1,1,31,42,120,61,0,17,92,4,...,0,0,0,0,225,0,11,341,0,0
1,1,2,31,42,120,60,0,17,88,4,...,0,1,0,4,267,0,6,256,0,0
2,1,3,31,42,120,60,0,17,88,4,...,0,1,0,8,307,0,4,206,0,0
3,1,4,31,42,120,58,0,18,88,4,...,0,0,0,0,334,0,4,206,0,0
4,1,5,31,42,120,58,0,18,88,4,...,0,0,0,0,353,0,4,260,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9283,23159,11,27,39,122,142,0,0,189,6,...,0,9,0,0,0,0,0,274,178,198
9284,23159,12,27,39,122,144,0,0,148,6,...,0,7,0,0,0,0,1,293,121,200
9285,23918,8,2,4,12,5,0,0,5,0,...,0,0,0,0,17,0,0,0,0,0
9286,23918,9,2,4,12,5,0,0,5,0,...,0,0,0,0,14,0,0,0,0,0
9287,23918,10,2,4,12,5,0,0,5,0,...,0,0,0,0,21,0,0,0,0,0

# 2018

## Cirugias

In [193]:
cirugias=pd.read_csv('Cirugias\ConsultaH_Intervenciones_Quirurgicas_2017_v1.csv',encoding='ISO-8859-1')

In [194]:
cirugias.replace('NE_0002', np.nan, inplace=True)
cirugias.replace('NE_0001', np.nan, inplace=True)
cirugias.fillna(0,inplace=True)

In [195]:
cirugias.iloc[:,10:]=cirugias.iloc[:,10:].apply(pd.to_numeric,errors='coerce')

In [199]:
cirugias.head()

,CO_IPRESS,ANHO,MES,DE_PROGRAMC,TOTAL_CIRUJ_MAY,TOTAL_CIRUJ_MEN,HORAS_PROGRAMADAS,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND
0,1,2017,1,3,207,30.0,315.0,301.0,0,5
1,1,2017,2,3,203,25.0,324.0,311.0,0,4
2,1,2017,3,3,190,28.0,321.0,315.0,0,3
3,1,2017,4,3,177,26.0,326.0,318.0,0,2
4,1,2017,5,3,167,26.0,306.0,298.0,0,3

In [197]:
cirugias_to_sum = cirugias.columns[10:]
cirugias=cirugias.groupby(['CO_IPRESS','ANHO','MES'])[cirugias_to_sum].sum()

In [198]:
cirugias=cirugias.reset_index()

## Procedimientos

In [200]:
procedimientos=pd.read_csv("Procedimientos\ConsultaG_Procedimientos_2017_v1.csv",encoding='ISO-8859-1')

C:\Users\gonza\AppData\Local\Temp\ipykernel_11100\76611569.py:1: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  procedimientos=pd.read_csv("Procedimientos\ConsultaG_Procedimientos_2017_v1.csv",encoding='ISO-8859-1')

In [201]:
procedimientos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PROCEDIMIENTO,PROCEDIMIENTO,TOTAL,ID_CODIGO,DES_DESCRIPCION
0,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,94010,"Espirometría, incluyendo reporte gráfico, capa...",1,223800,CONSULTA EXTERNA-NEUMOLOGÍA
1,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,96372,"Inyección terapéutica, profiláctica o diagnóst...",1,250100,UNIDAD DE CUIDADOS CRITICOS UNIDAD DE CUIDADO...
2,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,86704,Anticuerpo contra el antígeno de la nucleocáps...,2,150000,PATOLOGÍA CLÍNICA (LABORATORIO CLÍNICO)
3,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,84450,Aspartato amino transferasa (AST) (SGOT),1,150000,PATOLOGÍA CLÍNICA (LABORATORIO CLÍNICO)
4,2017,4,40103,AREQUIPA,AREQUIPA,CAYMA,PRIVADO,II-1,15730,CLINICA SAN JUAN DE DIOS,93784,"Control ambulatorio de la presión arterial, me...",3,222500,CONSULTA EXTERNA-CARDIOLOGÍA

In [202]:
procedimientos=procedimientos.groupby(['CO_IPRESS','MES','ANHO'])['ID_PROCEDIMIENTO'].count().reset_index()

In [203]:
procedimientos

      CO_IPRESS  MES  ANHO  ID_PROCEDIMIENTO
0             1    1  2017               629
1             1    2  2017               580
2             1    3  2017               542
3             1    4  2017               534
4             1    5  2017               603
...         ...  ...   ...               ...
9493      23159   11  2017              2921
9494      23159   12  2017              3291
9495      23918    8  2017                12
9496      23918    9  2017                12
9497      23918   10  2017                13

[9498 rows x 4 columns]

## Complicaciones

In [204]:
complicaciones=pd.read_csv("Complcaciones\ConsultaF_Consolidado_Eventos_2017_v1.csv",encoding='ISO-8859-1')

In [205]:
complicaciones.replace('NE_0002', np.nan, inplace=True)
complicaciones.replace('NE_0001', np.nan, inplace=True)
complicaciones.fillna(0,inplace=True)

In [206]:
complicaciones.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,EVENTOS,CANT_EVENTOS
0,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Nacidos vivos con bajo peso al nacer (< 2500 grs),3
1,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Nacidos vivos con edad gestacional menor a 37 ...,3
2,2017,6,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de Infeccion Intrahosp...,1
3,2017,8,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de infeccion de herida ...,1
4,2017,8,150122,LIMA,LIMA,MIRAFLORES,PRIVADO,II-2,8746,CLINICA GOOD HOPE,Numero de Casos Nuevos de infeccion de herida ...,1

In [207]:
complicaciones.iloc[:,-1]=complicaciones.iloc[:,-1].apply(pd.to_numeric)

In [208]:
complicaciones = pd.pivot_table(complicaciones, values='CANT_EVENTOS', index=['ANHO', 'MES', 'UBIGEO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'SECTOR', 'CATEGORIA', 'CO_IPRESS', 'RAZON_SOC'], columns='EVENTOS', aggfunc='sum', fill_value=0)
complicaciones.reset_index(inplace=True)
complicaciones

EVENTOS,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,ESSALUD,II-1,9066,HOSPITAL HIGOS URCO,...,0,0,0,0,164,0,0,24,0,21
1,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,GOBIERNO REGIONAL,II-2,4838,HOSPITAL REGIONAL VIRGEN DE FATIMA,...,0,0,0,0,18,0,2,0,0,0
2,2017,1,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,13226,POLICLINICO PNP CHACHAPOYAS,...,0,0,0,0,0,0,0,0,0,0
3,2017,1,10201,AMAZONAS,BAGUA,BAGUA,ESSALUD,II-1,9068,HOSPITAL I HEROES DEL CENEPA,...,0,0,0,0,52,0,0,15,15,15
4,2017,1,10201,AMAZONAS,BAGUA,BAGUA,GOBIERNO REGIONAL,II-1,5044,HOSPITAL DE APOYO GUSTAVO LANATTA LUJAN,...,0,0,0,0,124,1,0,15,16,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9671,2017,12,240304,TUMBES,ZARUMILLA,PAPAYAL,GOBIERNO REGIONAL,I-3,1891,C.S. PAPAYAL,...,0,0,0,0,7,0,0,0,0,0
9672,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,ESSALUD,II-2,9600,HOSPITAL II PUCALLPA- ESSALUD,...,0,0,0,0,512,0,0,126,79,102
9673,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,PRIVADO,I-3,10505,SERVICIOS GENERALES SERFARMED SYS S.A,...,0,0,0,0,0,0,0,0,0,0
9674,2017,12,250101,UCAYALI,CORONEL PORTILLO,CALLERIA,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,10148,POLICLINICO SANIDAD DE LA POLICIA NACIONAL DEL...,...,0,0,0,0,0,0,0,0,0,0
9675,2017,12,250105,UCAYALI,CORONEL PORTILLO,YARINACOCHA,GOBIERNO REGIONAL,II-2,5577,HOSPITAL AMAZONICO - YARINACOCHA,...,0,0,0,0,215,0,3,44,122,193

In [214]:
colums_to_sum=complicaciones.columns[-21:]

In [216]:
complicaciones.groupby(['CO_IPRESS','MES','ANHO'])[colums_to_sum].sum().reset_index()

EVENTOS,CO_IPRESS,MES,ANHO,Casos Nuevos de Gestantes con diagnostico confirmado de Tuberculosis,Casos Nuevos de Gestantes con diagnostico confirmado de infección HIV.,Casos Nuevos de TBC Multidrogoresistente (MDR o XDR).,Casos Nuevos de TBC pulmonar en el personal del EESS,Casos nuevos de infeccion HIV.,Fallecimientos en todos los servicios.,Nacidos vivos con bajo peso al nacer (< 2500 grs),...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,1,1,2017,0,0,0,0,2,18,10,...,0,0,0,0,225,0,11,341,0,0
1,1,2,2017,0,0,0,0,7,19,11,...,0,1,0,4,267,0,6,256,0,0
2,1,3,2017,0,0,0,0,5,5,3,...,0,1,0,8,307,0,4,206,0,0
3,1,4,2017,0,0,0,0,4,10,3,...,0,0,0,0,334,0,4,206,0,0
4,1,5,2017,0,0,0,0,0,12,1,...,0,0,0,0,353,0,4,260,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9671,23159,12,2017,0,0,0,0,3,0,24,...,0,7,0,0,0,0,1,293,121,200
9672,23578,12,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9673,23918,8,2017,0,0,0,0,0,0,0,...,0,0,0,0,17,0,0,0,0,0
9674,23918,9,2017,0,0,0,0,0,0,0,...,0,0,0,0,14,0,0,0,0,0
9675,23918,10,2017,0,0,0,0,0,0,0,...,0,0,0,0,21,0,0,0,0,0

## Nacimientos

In [129]:
nacimientos=pd.read_csv("Nacimientos\ConsultaE_Consolidado_Partos_2017_v1_0.csv",encoding='ISO-8859-1')

In [130]:
nacimientos.replace('NE_0002', np.nan, inplace=True)
nacimientos.replace('NE_0001', np.nan, inplace=True)
nacimientos.fillna(0,inplace=True)

In [131]:
nac_red=nacimientos.copy()
nacimientos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PARTO,TIPO_PARTO,PARTOS_TOTAL,PARTOS_VIVOS,PARTOS_MUERTOS
0,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0
1,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0
2,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,01,VAGINAL,0,0,0
3,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,01,VAGINAL,11,11,0
4,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,02,CESAREA,0,0,0

In [132]:
nacimientos.iloc[:,-3:]=nacimientos.iloc[:,-3:].apply(pd.to_numeric)

In [133]:
import pandas as pd

nacimientos['Partos_CESAREA'] = 0
nacimientos['Partos_vivos_CESAREA'] = 0
nacimientos['Partos_muertos_CESAREA'] = 0
nacimientos['Partos_VAGINAL'] = 0
nacimientos['Partos_vivos_VAGINAL'] = 0
nacimientos['Partos_muertos_VAGINAL'] = 0

cesarea_condition = nacimientos['TIPO_PARTO'] == 'CESAREA'
vaginal_condition = nacimientos['TIPO_PARTO'] == 'VAGINAL'

nacimientos.loc[cesarea_condition, 'Partos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_TOTAL']
nacimientos.loc[vaginal_condition, 'Partos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_TOTAL']

nacimientos.loc[cesarea_condition, 'Partos_vivos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_VIVOS']
nacimientos.loc[cesarea_condition, 'Partos_muertos_CESAREA'] = nacimientos.loc[cesarea_condition, 'PARTOS_MUERTOS']

nacimientos.loc[vaginal_condition, 'Partos_vivos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_VIVOS']
nacimientos.loc[vaginal_condition, 'Partos_muertos_VAGINAL'] = nacimientos.loc[vaginal_condition, 'PARTOS_MUERTOS']

nacimientos.drop(['PARTOS_TOTAL','PARTOS_VIVOS','PARTOS_MUERTOS','ID_PARTO','TIPO_PARTO'],axis=1,inplace=True)

In [135]:
nacimientos

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,Partos_CESAREA,Partos_vivos_CESAREA,Partos_muertos_CESAREA,Partos_VAGINAL,Partos_vivos_VAGINAL,Partos_muertos_VAGINAL
0,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
1,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
2,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
3,2017,7,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,11,11,0
4,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18677,2017,5,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18678,2017,10,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18679,2017,12,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18680,2017,7,150133,LIMA,LIMA,SAN JUAN DE MIRAFLORES,SANIDAD DEL EJERCITO DEL PERU,I-3,10385,"CENTRO DE SALUD MILITAR ""SAN JUAN""",0,0,0,0,0,0
18681,2017,12,20102,ANCASH,HUARAZ,COCHABAMBA,GOBIERNO REGIONAL,I-2,1730,PUESTO DE SALUD COCHABAMBA,0,0,0,0,0,0

In [142]:
nacimientos=nacimientos.groupby(['CO_IPRESS','MES'])[['Partos_CESAREA','Partos_VAGINAL','Partos_vivos_CESAREA','Partos_vivos_VAGINAL','Partos_muertos_CESAREA','Partos_muertos_VAGINAL']].sum()
nacimientos=nacimientos.reset_index()

In [143]:
nacimientos

,CO_IPRESS,MES,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,99,241,94,240,6,0
1,1,2,65,191,75,196,0,0
2,1,3,73,190,74,196,0,0
3,1,4,90,180,88,181,2,0
4,1,5,101,192,100,192,1,0
...,...,...,...,...,...,...,...,...
9884,23159,12,160,151,161,146,2,5
9885,23578,12,0,0,0,0,0,0
9886,23918,8,6,1,6,1,0,0
9887,23918,9,5,2,5,2,0,0
9888,23918,10,5,2,5,2,0,0

In [112]:
nac_red[nac_red['CO_IPRESS']==3]

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_PARTO,TIPO_PARTO,PARTOS_TOTAL,PARTOS_VIVOS,PARTOS_MUERTOS
18034,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,7,1
18035,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,120,120,0
18036,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,34,33,2
18037,2017,7,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,158,158,0
18038,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,6,3
18039,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,130,130,0
18040,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,38,33,6
18041,2017,6,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,148,148,0
18042,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,15,11,6
18043,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,148,148,0
18044,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,52,54,3
18045,2017,3,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,139,139,0
18046,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,2,4
18047,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,132,132,0
18048,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,33,34,2
18049,2017,10,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,156,156,0
18050,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,7,3
18051,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,134,134,0
18052,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,59,60,1
18053,2017,4,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,137,137,0
18054,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,11,1
18055,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,124,124,0
18056,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,22,22,1
18057,2017,8,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,147,147,0
18058,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,6,3
18059,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,122,122,0
18060,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,34,33,2
18061,2017,5,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,133,133,0
18062,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,11,9,5
18063,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,114,114,0
18064,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,32,32,1
18065,2017,9,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,118,118,0
18066,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,4,3,1
18067,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,113,117,0
18068,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,55,54,1
18069,2017,2,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,101,101,0
18070,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,8,8,0
18071,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,103,103,2
18072,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,67,71,1
18073,2017,1,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,103,103,0
18074,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,11,16,2
18075,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,135,135,0
18076,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,5,0,5
18077,2017,11,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,175,175,0
18078,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,6,9,0
18079,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",02,CESAREA,154,154,0
18080,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,33,32,2
18081,2017,12,160108,LORETO,MAYNAS,PUNCHANA,GOBIERNO REGIONAL,III-1,3,"HOSPITAL REGIONAL DE LORETO ""FELIPE SANTIAGO A...",01,VAGINAL,146,146,0

## HospxEsp

In [174]:
espe=pd.read_csv("Espe\ConsultaD1_Hospitalizaciones_Especialidad_2017_v1.csv",encoding='ISO-8859-1')

C:\Users\gonza\AppData\Local\Temp\ipykernel_11100\958217491.py:1: DtypeWarning: Columns (10,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  espe=pd.read_csv("Espe\ConsultaD1_Hospitalizaciones_Especialidad_2017_v1.csv",encoding='ISO-8859-1')

In [175]:
espe.replace('NE_0002', np.nan, inplace=True)
espe.replace('NE_0001', np.nan, inplace=True)
espe.fillna(0,inplace=True)

In [176]:
espe.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,ID_HOSPITALIZACION,HOSPITALIZACION,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,2017,8,150112,LIMA,LIMA,INDEPENDENCIA,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-2,12741,POSTA MEDICA PNP INDEPENDENCIA,0,0,0,0,0,0,0,0,0
1,2017,8,150135,LIMA,LIMA,SAN MARTIN DE PORRES,SANIDAD DE LA POLICIA NACIONAL DEL PERU,I-3,11876,UNIDAD EJECUTORA 020: SANIDAD DE LA PNP,0,0,0,0,0,0,0,0,0
2,2017,8,150101,LIMA,LIMA,LIMA,PRIVADO,II-2,8281,CLINICAS MAISON DE SANTE SOCIEDAD ANONIMA,240000,HOSPITALIZACIÓN,40,40,195,207,23,713,0
3,2017,8,150101,LIMA,LIMA,LIMA,PRIVADO,II-2,8281,CLINICAS MAISON DE SANTE SOCIEDAD ANONIMA,240100,HOSPITALIZACIÓN QUIRÚRGICA CIRUGÍA GENERAL,37,37,165,223,26,806,0
4,2017,7,200104,PIURA,PIURA,CASTILLA,PRIVADO,II-E,13165,CENTRO DE REPOSO SAN JUAN DE DIOS,242202,HOSPITALIZACIÓN DE MEDICINA PSIQUIATRÍA PSIQUI...,48,52,1597,1424,56,1736,0

In [177]:
espe.iloc[:,-7:]=espe.iloc[:,-7:].apply(pd.to_numeric)

In [178]:
espe=espe.groupby(['CO_IPRESS','MES'])[['NRO_TOTAL_HOSPIT_ING','NRO_TOTAL_HOSPIT_EGR','NRO_TOTAL_ESTANCIAS','NRO_TOTAL_PACIENTES_CAMAS','NRO_TOTAL_CAMAS','NRO_TOTAL_CAMAS_DISPONIB','NRO_TOTAL_FALLECIDOS']].sum()

In [180]:
espe=espe.reset_index()
espe

,CO_IPRESS,MES,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,1,1,736,801,2762,3277,120,3720,18
1,1,2,555,632,2179,2181,120,3360,8
2,1,3,542,614,1994,1859,120,3720,5
3,1,4,580,661,2274,1995,120,3600,10
4,1,5,651,718,2507,1995,120,3720,12
...,...,...,...,...,...,...,...,...,...
10159,23159,12,472,459,4452,3417,152,4712,29
10160,23578,12,0,0,0,0,0,0,0
10161,23918,8,31,36,49,49,12,360,0
10162,23918,9,33,38,52,52,12,360,0
10163,23918,10,38,36,54,54,12,360,0

## Recursos

In [120]:
recursos=pd.read_csv("Recursos\ConsultaA_Recurso_Salud_2017_v1.csv",encoding='ISO-8859-1')

In [122]:
recursos.replace('NE_0002', np.nan, inplace=True)
recursos.replace('NE_0001', np.nan, inplace=True)
recursos.fillna(0,inplace=True)

In [123]:
recursos.head()

,ANHO,MES,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,SECTOR,CATEGORIA,CO_IPRESS,RAZON_SOC,...,CA_ENFERMERAS,CA_ODONTOLOGOS,CA_PSICOLOGOS,CA_NUTRICIONISTAS,CA_TECNOLOGOS_MEDICOS,CA_OBSTETRICES,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS
0,2017,12,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
1,2017,9,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,9,3,3,2,1,10,1,2,2,1
2,2017,11,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
3,2017,10,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,10,3,3,1,1,11,1,7,31,1
4,2017,8,70102,CALLAO,CALLAO,BELLAVISTA,GOBIERNO REGIONAL,I-4,6249,C.S. BELLAVISTA PERU COREA,...,9,3,3,2,1,10,1,2,2,1

In [124]:
recursos.iloc[:,10:26]=recursos.iloc[:,10:26].apply(pd.to_numeric)

In [128]:
columns_to_sum = recursos.columns[10:26]
recursos = recursos.groupby(['CO_IPRESS', 'MES'])[columns_to_sum].sum()
recursos = recursos.reset_index()
recursos

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,CA_PSICOLOGOS,CA_NUTRICIONISTAS,CA_TECNOLOGOS_MEDICOS,CA_OBSTETRICES,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS
0,1,1,31,42,120,61,0,17,92,4,2,3,1,38,7,252,3,1
1,1,2,31,42,120,60,0,17,88,4,2,3,1,37,7,252,5,1
2,1,3,31,42,120,60,0,17,88,4,2,3,1,37,7,252,5,1
3,1,4,31,42,120,58,0,18,88,4,2,3,1,33,6,252,5,1
4,1,5,31,42,120,58,0,18,88,4,2,3,1,33,6,252,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9974,23159,12,27,39,122,144,0,0,148,6,4,6,43,37,16,280,1,2
9975,23578,12,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0
9976,23918,8,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0
9977,23918,9,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0
9978,23918,10,2,4,12,5,0,0,5,0,0,1,1,4,1,9,3,0

## base final

In [171]:
nacimientos.head()

,CO_IPRESS,MES,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,99,241,94,240,6,0
1,1,2,65,191,75,196,0,0
2,1,3,73,190,74,196,0,0
3,1,4,90,180,88,181,2,0
4,1,5,101,192,100,192,1,0

In [173]:
df = pd.merge(recursos, nacimientos, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CA_FARMACEUTICOS,CA_AUXILIARES,CA_OTROS_PROF,CA_AMBULANCIAS,Partos_CESAREA,Partos_VAGINAL,Partos_vivos_CESAREA,Partos_vivos_VAGINAL,Partos_muertos_CESAREA,Partos_muertos_VAGINAL
0,1,1,31,42,120,61,0,17,92,4,...,7,252,3,1,99,241,94,240,6,0
1,1,2,31,42,120,60,0,17,88,4,...,7,252,5,1,65,191,75,196,0,0
2,1,3,31,42,120,60,0,17,88,4,...,7,252,5,1,73,190,74,196,0,0
3,1,4,31,42,120,58,0,18,88,4,...,6,252,5,1,90,180,88,181,2,0
4,1,5,31,42,120,58,0,18,88,4,...,6,252,5,1,101,192,100,192,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9783,23159,12,27,39,122,144,0,0,148,6,...,16,280,1,2,160,151,161,146,2,5
9784,23578,12,0,0,0,1,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
9785,23918,8,2,4,12,5,0,0,5,0,...,1,9,3,0,6,1,6,1,0,0
9786,23918,9,2,4,12,5,0,0,5,0,...,1,9,3,0,5,2,5,2,0,0
9787,23918,10,2,4,12,5,0,0,5,0,...,1,9,3,0,5,2,5,2,0,0

In [217]:
df = pd.merge(df, cirugias, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CA_OTROS_PROF,CA_AMBULANCIAS,ANHO,DE_PROGRAMC,TOTAL_CIRUJ_MAY,TOTAL_CIRUJ_MEN,HORAS_PROGRAMADAS,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND
0,1,1,31,42,120,61,0,17,92,4,...,3,1,2017,3,207,30.0,315.0,301.0,0,5
1,1,2,31,42,120,60,0,17,88,4,...,5,1,2017,3,203,25.0,324.0,311.0,0,4
2,1,3,31,42,120,60,0,17,88,4,...,5,1,2017,3,190,28.0,321.0,315.0,0,3
3,1,4,31,42,120,58,0,18,88,4,...,5,1,2017,3,177,26.0,326.0,318.0,0,2
4,1,5,31,42,120,58,0,18,88,4,...,5,1,2017,3,167,26.0,306.0,298.0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9623,23159,12,27,39,122,144,0,0,148,6,...,1,2,2017,3,353,75.0,480.0,715.0,0,11
9624,23578,12,0,0,0,1,0,0,0,0,...,0,0,2017,0,0,0.0,0.0,0.0,0.0,0
9625,23918,8,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,31.0,87.0,74.0,0,0
9626,23918,9,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,33.0,99.0,79.0,0,0
9627,23918,10,2,4,12,5,0,0,5,0,...,3,0,2017,1,0,38.0,144.0,91.0,0,0

In [218]:
df = pd.merge(df, espe, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,HORAS_EFECTIVAS,HORAS_ACT_QUIRURJ,CIRUJ_SUSPEND,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS
0,1,1,31,42,120,61,0,17,92,4,...,301.0,0,5,736,801,2762,3277,120,3720,18
1,1,2,31,42,120,60,0,17,88,4,...,311.0,0,4,555,632,2179,2181,120,3360,8
2,1,3,31,42,120,60,0,17,88,4,...,315.0,0,3,542,614,1994,1859,120,3720,5
3,1,4,31,42,120,58,0,18,88,4,...,318.0,0,2,580,661,2274,1995,120,3600,10
4,1,5,31,42,120,58,0,18,88,4,...,298.0,0,3,651,718,2507,1995,120,3720,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9567,23159,12,27,39,122,144,0,0,148,6,...,715.0,0,11,472,459,4452,3417,152,4712,29
9568,23578,12,0,0,0,1,0,0,0,0,...,0.0,0.0,0,0,0,0,0,0,0,0
9569,23918,8,2,4,12,5,0,0,5,0,...,74.0,0,0,31,36,49,49,12,360,0
9570,23918,9,2,4,12,5,0,0,5,0,...,79.0,0,0,33,38,52,52,12,360,0
9571,23918,10,2,4,12,5,0,0,5,0,...,91.0,0,0,38,36,54,54,12,360,0

In [219]:
df = pd.merge(df, procedimientos, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,CIRUJ_SUSPEND,NRO_TOTAL_HOSPIT_ING,NRO_TOTAL_HOSPIT_EGR,NRO_TOTAL_ESTANCIAS,NRO_TOTAL_PACIENTES_CAMAS,NRO_TOTAL_CAMAS,NRO_TOTAL_CAMAS_DISPONIB,NRO_TOTAL_FALLECIDOS,ANHO_y,ID_PROCEDIMIENTO
0,1,1,31,42,120,61,0,17,92,4,...,5,736,801,2762,3277,120,3720,18,2017,629
1,1,2,31,42,120,60,0,17,88,4,...,4,555,632,2179,2181,120,3360,8,2017,580
2,1,3,31,42,120,60,0,17,88,4,...,3,542,614,1994,1859,120,3720,5,2017,542
3,1,4,31,42,120,58,0,18,88,4,...,2,580,661,2274,1995,120,3600,10,2017,534
4,1,5,31,42,120,58,0,18,88,4,...,3,651,718,2507,1995,120,3720,12,2017,603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9313,23159,11,27,39,122,142,0,0,189,6,...,9,503,455,3966,3288,152,4560,10,2017,2921
9314,23159,12,27,39,122,144,0,0,148,6,...,11,472,459,4452,3417,152,4712,29,2017,3291
9315,23918,8,2,4,12,5,0,0,5,0,...,0,31,36,49,49,12,360,0,2017,12
9316,23918,9,2,4,12,5,0,0,5,0,...,0,33,38,52,52,12,360,0,2017,12
9317,23918,10,2,4,12,5,0,0,5,0,...,0,38,36,54,54,12,360,0,2017,13

In [220]:
df = pd.merge(df, complicaciones, on=['CO_IPRESS', 'MES'])
df

,CO_IPRESS,MES,CA_CONSULTORIOS,CA_CONSULTORIOS_FN,CA_CAMAS,CA_MEDICOS_TOTAL,CA_MEDICOS_SERUM,CA_MEDICOS_RESIDENTES,CA_ENFERMERAS,CA_ODONTOLOGOS,...,Numero de Casos Nuevos de Infeccion Intrahospitalaria en Gineco obstetricia,Numero de Casos Nuevos de Infeccion Intrahospitalaria en UCI,Numero de Casos Nuevos de Infección del tracto urinario por cateter,Numero de Casos Nuevos de infeccion de herida operatoria,Numero de Controles Prenatales realizados.,Numero de muertes maternas,Numero de muertes neonatales (menos de 28 dias de nacido),Partos en Gestantes que han recibido por lo menos un control prenatal en la IPRESS,Partos en gestante que han recibido la primera consulta prenatal en el primer trimestre del embarazo,Partos que se producen en gestantes que han recibido por lo menos 6 controles prenatales.
0,1,1,31,42,120,61,0,17,92,4,...,0,0,0,0,225,0,11,341,0,0
1,1,2,31,42,120,60,0,17,88,4,...,0,1,0,4,267,0,6,256,0,0
2,1,3,31,42,120,60,0,17,88,4,...,0,1,0,8,307,0,4,206,0,0
3,1,4,31,42,120,58,0,18,88,4,...,0,0,0,0,334,0,4,206,0,0
4,1,5,31,42,120,58,0,18,88,4,...,0,0,0,0,353,0,4,260,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9283,23159,11,27,39,122,142,0,0,189,6,...,0,9,0,0,0,0,0,274,178,198
9284,23159,12,27,39,122,144,0,0,148,6,...,0,7,0,0,0,0,1,293,121,200
9285,23918,8,2,4,12,5,0,0,5,0,...,0,0,0,0,17,0,0,0,0,0
9286,23918,9,2,4,12,5,0,0,5,0,...,0,0,0,0,14,0,0,0,0,0
9287,23918,10,2,4,12,5,0,0,5,0,...,0,0,0,0,21,0,0,0,0,0